htd_admin:
    resource: "@HTDAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

htd_app:
    resource: "@HTDAppBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
