htd_admin:
    resource: "@HTDAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

HTDAdminBundle_admin_htd_admin_bundle_contact:
    resource: "@HTDAdminBundle/Controller/Contact/"
    type:     admingenerator
    prefix:   /admin/contact

HTDAdminBundle_admin_htd_admin_bundle_artist:
    resource: "@HTDAdminBundle/Controller/Artist/"
    type:     admingenerator
    prefix:   /admin/artist

HTDAdminBundle_admin_htd_admin_bundle__product:
    resource: "@HTDAdminBundle/Controller/Product/"
    type:     admingenerator
    prefix:   /admin/product

htd_app:
    resource: "@HTDAppBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
